### PR TITLE
553 - Fix Download Files Summary Component

### LINKED ISSUE #553: Fix Download Files Summary Component
### Context

**QA Feedback:** [Thread](https://github.com/AlexsLemonade/refinebio-web/issues/525#issuecomment-2831532669)

During QA, we discovered that the number of download files displayed in the UI doesn't match the actual number of downloads and it needs to be addressed.

### Problem or idea

We will update the `DatasetFileSummary` to display the file summary details as follows:

- 1 Gene Expression file per aggregate (`EXPERIMENT`/`SPECIES`)
- 1 Sample Metadata file per aggregate (`EXPERIMENT`/`SPECIES`)
- 1 Aggregate Metadata file per aggregate (`EXPERIMENT`/`SPECIES`) with "1 file per download" (fixed)

### Solution or next step

- Update the `DatasetFileSummary` to accurately display the file details to make sure that the UI reflects the actual contents of the downloaded zip files

### PR DESCRIPTION
**Pull request by nozomione**
## Issue Number

Closes #553

## Purpose/Implementation Notes

I've adjust the `Download Files Summary` UI to match the contents of the downloaded zip files. 

@dvenprasad, please see the latest UI [here](https://refinebio-web-git-nozomione-553-fix-download-files-793c00-ccdl.vercel.app/) -  It aligns with the download folder structure listed in the [docs](https://docs.refine.bio/en/latest/main_text.html#downloadable-files). Thank you! 

## Types of changes

- Bugfix (non-breaking change which fixes an issue)

## Functional tests

N/A

## Checklist

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Screenshots

N/A

### CODE REVIEW

File: src/helpers/getDownloadFilesData.js [hunk 1]
```diff
@@ -16,15 +16,13 @@ export default (dataset) => {
...
+        title: `${totalCount} Sample Metadata Files`,
+        description: `1 file per ${aggregateBy}`,
         format: 'tsv'
       },
       {
-        title: `${totalCount} ${aggregateBy} Metadata ${
-          isExperiment ? 'Files' : ''
-        }`,
-        description: `1 file per ${aggregateBy}`,
+        title: '1 Aggregate Metadata File',
```
Comment (davidsmejia) [inline src/helpers/getDownloadFilesData.js:24]:
```suggestion
        title: '1 ${aggregateBy} Metadata File',
```

**Review by davidsmejia — APPROVED** [review]
